image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Push to GitHub
          script:         
            - git config --global user.email "deploy@telr.com"
            - git config --global user.name "deploy"
            - git remote add github https://github.com/Telr-PG/telr-sdk-ios-mpi-sample
            - git push https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/Telr-PG/telr-sdk-ios-mpi-sample HEAD:refs/heads/main
